### PR TITLE
Improve minibatch iteration

### PR DESCRIPTION
**Pull request by akosiorek**
* implement MinibatchIterator class - a reusable iterator over minibatches
* return an instance of MinibatchIterator from minibatches fun
* the new iterator creates 1 minibatch at a time saving GPU memory

### CODE REVIEW

**Comment by akosiorek** [comment]
We might want to add `n_cycles` and randomization to `MinibatchIterator`'s interface instead of doing that separately in `iter_minibatches`. What do you think?

**Comment by bayerj** [comment]
Can you elaborate why you chose to implement a new class instead of extending the previous iterator? The iterator is part of the public API and thus probably part of many user programs. Adding a new part with a little bit of more functionality might be confusing.

**Comment by akosiorek** [comment]
The class solves the problem of PR #37 by creating a reusable random-access iterator. It can be used exactly like `minibatches` output and preserves the API, but does not create all the batches at once, yet is cleaner than #37. PR is a result of discussion with @msoelch. I chose to put `MinibatchIterator` outside of `minibatches` to allow its direct use, e.g., in Breze.

**Comment by bayerj** [comment]
I am just worried that line 13 of the zen of python is violated here.

Adam Kosiorek <notifications@github.com> schrieb am Do., 14. Juli 2016 um
14:35 Uhr:

**Comment by msoelch** [comment]
Cf. newest comment in #37 

@bayerj might be right here. We are checking out a minimally invasive, backward compatible version that does not add functionality to climin that it should not have.

**Comment by msoelch** [comment]
This has been fixed with a modified version of the previous PR.

**Pull request closed without merging**
